### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tycobbb** [surrealdetective/witnessslips#1]
- [x] Scrape witness slips with undetermined metadata from gov't
- [x] Warehouse data in the context of some webserver
- [x] Build out an API that can be used by other applications and people
- [ ] Build admin tool to allow users to browse active bills and modify or add data.
- [ ] Build a tool to send informational notifications along social channels

**Comment by tycobbb** [comment]
Let's use this issue for now to track our progress, figure out what needs to be done, if we're going in the right direction, etc.

If someone has another tool they want to use for project tracking let's talk about that too!

**Comment by tycobbb** [comment]
I updated the scraper to collect all the bills for the current month and apply some structure to the data. It can now dump its output as JSON, sample below.

@justgosh I think in this state we can probably start to think about replacing large chunks of the manual work going into the Google doc. Can we get in contact with any of its maintainers outside of Facebook? I think it'd be wise to ask them some questions about if and how they'd like that document generated.

```
{
  "chambers": [
    {
      "name": "House",
      "hearings": [
        {
          "url": "<omitted for brevity>",
          "committee_name": "Appropriations-Human Services Committee",
          "location": "Capitol Building - Room 114 - Springfield, IL",
          "date": "3/09/2017",
          "time": "8:00 AM",
          "bills": [
            {
              "number": "HB3986",
              "description": "$DHFS FY18 OCE",
              "sponsor_name": "Jim Durkin",
              "witness_slip_url": "http://my.ilga.gov/WitnessSlip/Create/106057?committeeHearingId=14328&LegislationId=106057&HCommittees4%2F8%2F2017-page=1&committeeid=0&chamber=H&nodays=30&_=1489042607127"
            },
            <more bills>
          ]
        },
        <more hearings>
      ]
    },
    <more chambers>
  ]
}
```

**Comment by justgosh** [comment]
Well done!
This is the current preferred format
https://docs.google.com/spreadsheets/d/1u7s4x4Kp4xpjWB9KKp-dN8BiZAS-9VdlkM4U8_-KASM/edit#gid=557405430
 You'll notice that the preferred doc has more data than what's in this
scrape.  Leaving those boxes blank for now should be fine.
Thanks!
